version: '2'
services:
  app:
    build: docker/app
    volumes:
      - .:/var/www
    working_dir: /var/www
  web:
    image: nginx:1.15
    volumes:
      - ./etc/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    working_dir: /var/www
    ports:
      - 8080:80
